# enclii.yaml — Tezca service onboarding spec
# https://docs.enclii.dev/onboarding

project: tezca
namespace: tezca
org: madfam-org
registry: ghcr.io/madfam-org/tezca

services:
  - name: tezca-api
    dockerfile: apps/indigo/Dockerfile
    port: 8000
    health: /api/v1/admin/health/
    domains:
      - api.tezca.mx
    replicas:
      min: 2
      max: 6
    resources:
      memory: 512Mi-2Gi
      cpu: 250m-1000m

  - name: tezca-web
    dockerfile: apps/web/Dockerfile
    port: 3000
    health: /api/health
    domains:
      - tezca.mx
      - www.tezca.mx
    replicas:
      min: 2
      max: 5
    resources:
      memory: 128Mi-512Mi
      cpu: 100m-500m

  - name: tezca-admin
    dockerfile: apps/admin/Dockerfile
    port: 3001
    health: /api/health
    domains:
      - admin.tezca.mx
    replicas:
      min: 1
      max: 1
    resources:
      memory: 128Mi-256Mi
      cpu: 100m-250m

  - name: tezca-worker
    dockerfile: apps/indigo/Dockerfile
    command: ["celery", "-A", "apps.indigo", "worker", "--loglevel=info", "--concurrency=4"]
    replicas:
      min: 1
      max: 1
    resources:
      memory: 512Mi-2Gi
      cpu: 250m-1000m

  - name: tezca-beat
    dockerfile: apps/indigo/Dockerfile
    command: ["celery", "-A", "apps.indigo", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    replicas:
      min: 1
      max: 1
    singleton: true
    resources:
      memory: 256Mi-512Mi
      cpu: 100m-250m

  - name: tezca-redis
    image: redis:7-alpine
    port: 6379
    replicas:
      min: 1
      max: 1
    storage: 5Gi

  - name: tezca-es
    image: elasticsearch:7.17.9
    port: 9200
    replicas:
      min: 1
      max: 1
    storage: 50Gi
    env:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

secrets:
  - name: tezca-secrets
    keys:
      - django-secret-key
      - db-user
      - db-password
      - db-host
      - janua-api-key
      - janua-publishable-key
      - janua-secret-key
