# enclii.yaml — Tezca platform integration spec
# Parsed by Enclii webhook handler for domain provisioning
# https://docs.enclii.dev/onboarding
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: tezca-api
  project: tezca
spec:
  runtime:
    port: 8000
  domains:
    - name: api.tezca.mx
      environment: production
      port: 8000
    - name: tezca.mx
      environment: production
      port: 3000
    - name: www.tezca.mx
      environment: production
      port: 3000
    - name: admin.tezca.mx
      environment: production
      port: 3001
