# Generated by Django 5.2.10 on 2026-02-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_id",
                    models.CharField(
                        help_text="Slug identifier (e.g., 'cpeum')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name of the law", max_length=500),
                ),
                ("short_name", models.CharField(blank=True, max_length=200, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("tier", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LawVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(help_text="Date of publication in DOF"),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date this version became effective",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this version was superseded (null if current)",
                        null=True,
                    ),
                ),
                ("dof_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "xml_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.law",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date"],
                "indexes": [
                    models.Index(
                        fields=["law", "valid_from", "valid_to"],
                        name="api_lawvers_law_id_0c389d_idx",
                    )
                ],
            },
        ),
    ]
