# Generated by Django 5.2.11 on 2026-02-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='municipality',
            field=models.CharField(blank=True, help_text='Municipality name for municipal laws', max_length=100, null=True),
        ),
    ]
