# Generated by Django 5.2.10 on 2026-02-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_state_source_url_last_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="status",
            field=models.CharField(
                choices=[
                    ("vigente", "Vigente"),
                    ("abrogada", "Abrogada"),
                    ("derogada", "Derogada"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                help_text="Legal status: vigente, abrogada, derogada, unknown",
                max_length=20,
            ),
        ),
    ]
