# Generated by Django 5.2.10 on 2026-02-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_backfill_law_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, default="", max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("law_id", models.CharField(max_length=50)),
                ("format", models.CharField(max_length=10)),
                ("tier", models.CharField(default="anon", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="api_exportl_user_id_9ff18d_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="api_exportl_ip_addr_8926eb_idx",
                    ),
                ],
            },
        ),
    ]
