# Generated by Django 5.2.10 on 2026-02-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.IntegerField(
                        choices=[
                            (1, "Quick Wins"),
                            (2, "Institutional Outreach"),
                            (3, "New Scrapers"),
                            (4, "Partnerships"),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fix", "Fix"),
                            ("scraper", "New Scraper"),
                            ("outreach", "Outreach"),
                            ("investigation", "Investigation"),
                            ("partnership", "Partnership"),
                            ("infrastructure", "Infrastructure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("deferred", "Deferred"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("estimated_laws", models.IntegerField(default=0)),
                (
                    "estimated_effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=5)),
                ("sort_order", models.IntegerField(default=0)),
                ("progress_pct", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_gaps",
                    models.ManyToManyField(blank=True, to="dataops.gaprecord"),
                ),
                (
                    "related_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataops.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "sort_order", "priority"],
            },
        ),
    ]
