# This file has been generated by the Catala compiler, do not edit!

from catala.runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum

class Person:
    def __init__(self, tax_obligation: bool) -> None:
        self.tax_obligation = tax_obligation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Person):
            return (self.tax_obligation == other.tax_obligation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "Person(tax_obligation={})".format(self.tax_obligation)

class PhysicalPersonTax:
    def __init__(self, total_income: Money) -> None:
        self.total_income = total_income

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PhysicalPersonTax):
            return (self.total_income == other.total_income)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PhysicalPersonTax(total_income={})".format(self.total_income)

class PersonTest1:
    def __init__(self, result: bool) -> None:
        self.result = result

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PersonTest1):
            return (self.result == other.result)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PersonTest1(result={})".format(self.result)

class PersonIn:
    def __init__(self, residence_in: bool, income_source_mx_in: bool) -> None:
        self.residence_in = residence_in
        self.income_source_mx_in = income_source_mx_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PersonIn):
            return (self.residence_in == other.residence_in and
                   self.income_source_mx_in == other.income_source_mx_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PersonIn(residence_in={},income_source_mx_in={})".format(self.residence_in,
            self.income_source_mx_in)

class PhysicalPersonTaxIn:
    def __init__(self, income_cash_in: Money, income_goods_in: Money) -> None:
        self.income_cash_in = income_cash_in
        self.income_goods_in = income_goods_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PhysicalPersonTaxIn):
            return (self.income_cash_in == other.income_cash_in and
                   self.income_goods_in == other.income_goods_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PhysicalPersonTaxIn(income_cash_in={},income_goods_in={})".format(self.income_cash_in,
            self.income_goods_in)

class PersonTest1In:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PersonTest1In):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PersonTest1In()".format()



def person(person_in:PersonIn):
    residence = person_in.residence_in
    income_source_mx = person_in.income_source_mx_in
    try:
        def temp_tax_obligation(_:Unit):
            return False
        def temp_tax_obligation_1(_:Unit):
            return True
        def temp_tax_obligation_2(_:Unit):
            def temp_tax_obligation_3(_:Unit):
                raise EmptyError
            def temp_tax_obligation_4(_:Unit):
                return False
            def temp_tax_obligation_5(_:Unit):
                def temp_tax_obligation_6(_:Unit):
                    return True
                def temp_tax_obligation_7(_:Unit):
                    return residence
                def temp_tax_obligation_8(_:Unit):
                    def temp_tax_obligation_9(_:Unit):
                        return True
                    def temp_tax_obligation_10(_:Unit):
                        return (not residence and income_source_mx)
                    return handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                          start_line=5, start_column=10,
                                          end_line=5, end_column=24,
                                          law_headings=[]), [],
                                          temp_tax_obligation_10,
                                          temp_tax_obligation_9)
                return handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                      start_line=5, start_column=10,
                                      end_line=5, end_column=24,
                                      law_headings=[]), [temp_tax_obligation_8],
                                      temp_tax_obligation_7,
                                      temp_tax_obligation_6)
            return handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                  start_line=5, start_column=10,
                                  end_line=5, end_column=24,
                                  law_headings=[]), [temp_tax_obligation_5],
                                  temp_tax_obligation_4,
                                  temp_tax_obligation_3)
        temp_tax_obligation_11 = handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                                start_line=5,
                                                start_column=10,
                                                end_line=5, end_column=24,
                                                law_headings=[]), [temp_tax_obligation_2],
                                                temp_tax_obligation_1,
                                                temp_tax_obligation)
    except EmptyError:
        temp_tax_obligation_11 = dead_value
        raise NoValueProvided(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=5, start_column=10,
                                             end_line=5, end_column=24,
                                             law_headings=[]))
    tax_obligation = temp_tax_obligation_11
    return Person(tax_obligation = tax_obligation)

def physical_person_tax(physical_person_tax_in:PhysicalPersonTaxIn):
    income_cash = physical_person_tax_in.income_cash_in
    income_goods = physical_person_tax_in.income_goods_in
    try:
        def temp_total_income(_:Unit):
            return (income_cash + income_goods)
        def temp_total_income_1(_:Unit):
            return True
        temp_total_income_2 = handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=10, start_column=10,
                                             end_line=10, end_column=22,
                                             law_headings=[]), [],
                                             temp_total_income_1,
                                             temp_total_income)
    except EmptyError:
        temp_total_income_2 = dead_value
        raise NoValueProvided(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=10, start_column=10,
                                             end_line=10, end_column=22,
                                             law_headings=[]))
    total_income = temp_total_income_2
    return PhysicalPersonTax(total_income = total_income)

def person_test1(person_test1_in:PersonTest1In):
    try:
        def temp_result(_:Unit):
            raise EmptyError
        def temp_result_1(_:Unit):
            return False
        temp_result_2 = handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                       start_line=13, start_column=10,
                                       end_line=13, end_column=16,
                                       law_headings=[]), [], temp_result_1,
                                       temp_result)
    except EmptyError:
        temp_result_2 = dead_value
        raise NoValueProvided(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=13, start_column=10,
                                             end_line=13, end_column=16,
                                             law_headings=[]))
    result = temp_result_2
    return PersonTest1(result = result)
