# This file has been generated by the Catala compiler, do not edit!

from catala.runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum

class Person:
    def __init__(self, tax_obligation: bool) -> None:
        self.tax_obligation = tax_obligation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Person):
            return (self.tax_obligation == other.tax_obligation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "Person(tax_obligation={})".format(self.tax_obligation)

class PhysicalPersonTax:
    def __init__(self, total_income: Money) -> None:
        self.total_income = total_income

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PhysicalPersonTax):
            return (self.total_income == other.total_income)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PhysicalPersonTax(total_income={})".format(self.total_income)

class TaxCalculation2026:
    def __init__(self, tax_owed: Money) -> None:
        self.tax_owed = tax_owed

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaxCalculation2026):
            return (self.tax_owed == other.tax_owed)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TaxCalculation2026(tax_owed={})".format(self.tax_owed)

class PersonIn:
    def __init__(self, residence_in: bool, income_source_mx_in: bool) -> None:
        self.residence_in = residence_in
        self.income_source_mx_in = income_source_mx_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PersonIn):
            return (self.residence_in == other.residence_in and
                   self.income_source_mx_in == other.income_source_mx_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PersonIn(residence_in={},income_source_mx_in={})".format(self.residence_in,
            self.income_source_mx_in)

class PhysicalPersonTaxIn:
    def __init__(self, income_cash_in: Money, income_goods_in: Money) -> None:
        self.income_cash_in = income_cash_in
        self.income_goods_in = income_goods_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PhysicalPersonTaxIn):
            return (self.income_cash_in == other.income_cash_in and
                   self.income_goods_in == other.income_goods_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PhysicalPersonTaxIn(income_cash_in={},income_goods_in={})".format(self.income_cash_in,
            self.income_goods_in)

class TaxCalculation2026In:
    def __init__(self, monthly_income_in: Money) -> None:
        self.monthly_income_in = monthly_income_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaxCalculation2026In):
            return (self.monthly_income_in == other.monthly_income_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TaxCalculation2026In(monthly_income_in={})".format(self.monthly_income_in)



def person(person_in:PersonIn):
    residence = person_in.residence_in
    income_source_mx = person_in.income_source_mx_in
    try:
        def temp_tax_obligation(_:Unit):
            return False
        def temp_tax_obligation_1(_:Unit):
            return True
        def temp_tax_obligation_2(_:Unit):
            def temp_tax_obligation_3(_:Unit):
                raise EmptyError
            def temp_tax_obligation_4(_:Unit):
                return False
            def temp_tax_obligation_5(_:Unit):
                def temp_tax_obligation_6(_:Unit):
                    return True
                def temp_tax_obligation_7(_:Unit):
                    return residence
                def temp_tax_obligation_8(_:Unit):
                    def temp_tax_obligation_9(_:Unit):
                        return True
                    def temp_tax_obligation_10(_:Unit):
                        return (not residence and income_source_mx)
                    return handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                          start_line=11, start_column=10,
                                          end_line=11, end_column=24,
                                          law_headings=[]), [],
                                          temp_tax_obligation_10,
                                          temp_tax_obligation_9)
                return handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                      start_line=11, start_column=10,
                                      end_line=11, end_column=24,
                                      law_headings=[]), [temp_tax_obligation_8],
                                      temp_tax_obligation_7,
                                      temp_tax_obligation_6)
            return handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                  start_line=11, start_column=10,
                                  end_line=11, end_column=24,
                                  law_headings=[]), [temp_tax_obligation_5],
                                  temp_tax_obligation_4,
                                  temp_tax_obligation_3)
        temp_tax_obligation_11 = handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                                start_line=11,
                                                start_column=10,
                                                end_line=11, end_column=24,
                                                law_headings=[]), [temp_tax_obligation_2],
                                                temp_tax_obligation_1,
                                                temp_tax_obligation)
    except EmptyError:
        temp_tax_obligation_11 = dead_value
        raise NoValueProvided(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=11, start_column=10,
                                             end_line=11, end_column=24,
                                             law_headings=[]))
    tax_obligation = temp_tax_obligation_11
    return Person(tax_obligation = tax_obligation)

def physical_person_tax(physical_person_tax_in:PhysicalPersonTaxIn):
    income_cash = physical_person_tax_in.income_cash_in
    income_goods = physical_person_tax_in.income_goods_in
    try:
        def temp_total_income(_:Unit):
            return (income_cash + income_goods)
        def temp_total_income_1(_:Unit):
            return True
        temp_total_income_2 = handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=16, start_column=10,
                                             end_line=16, end_column=22,
                                             law_headings=[]), [],
                                             temp_total_income_1,
                                             temp_total_income)
    except EmptyError:
        temp_total_income_2 = dead_value
        raise NoValueProvided(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=16, start_column=10,
                                             end_line=16, end_column=22,
                                             law_headings=[]))
    total_income = temp_total_income_2
    return PhysicalPersonTax(total_income = total_income)

def tax_calculation2026(tax_calculation2026_in:TaxCalculation2026In):
    monthly_income = tax_calculation2026_in.monthly_income_in
    try:
        def temp_tax_owed(_:Unit):
            if ((monthly_income >= money_of_cents_string("1")) and
                (monthly_income <=
                money_of_cents_string("1013511"))):
                return (money_of_cents_string("0") + ((monthly_income -
                    money_of_cents_string("1")) *
                    decimal_of_string("0.0192")))
            else:
                if ((monthly_income >= money_of_cents_string("1013512")) and
                    (monthly_income <=
                    money_of_cents_string("8602211"))):
                    return (money_of_cents_string("19459") +
                        ((monthly_income -
                        money_of_cents_string("1013512")) *
                        decimal_of_string("0.064")))
                else:
                    if ((monthly_income >=
                        money_of_cents_string("8602212")) and
                        (monthly_income <=
                        money_of_cents_string("15117619"))):
                        return (money_of_cents_string("505137") +
                            ((monthly_income -
                            money_of_cents_string("8602212")) *
                            decimal_of_string("0.1088")))
                    else:
                        if ((monthly_income >=
                            money_of_cents_string("15117620")) and
                            (monthly_income <=
                            money_of_cents_string("17573566"))):
                            return (money_of_cents_string("1214013") +
                                ((monthly_income -
                                money_of_cents_string("15117620")) *
                                decimal_of_string("0.16")))
                        else:
                            if ((monthly_income >=
                                money_of_cents_string("17573567")) and
                                (monthly_income <=
                                money_of_cents_string("21040369"))):
                                return (money_of_cents_string("1606964") +
                                    ((monthly_income -
                                    money_of_cents_string("17573567")) *
                                    decimal_of_string("0.1792")))
                            else:
                                if ((monthly_income >=
                                    money_of_cents_string("21040370")) and
                                    (monthly_income <=
                                    money_of_cents_string("42435397"))):
                                    return (money_of_cents_string("2228214") +
                                        ((monthly_income -
                                        money_of_cents_string("21040370")) *
                                        decimal_of_string("0.2136")))
                                else:
                                    if ((monthly_income >=
                                        money_of_cents_string("42435398")) and
                                        (monthly_income <=
                                        money_of_cents_string("66884014"))):
                                        return (money_of_cents_string("6798192") +
                                            ((monthly_income -
                                            money_of_cents_string("42435398")) *
                                            decimal_of_string("0.2352")))
                                    else:
                                        if ((monthly_income >=
                                            money_of_cents_string("66884015")) and
                                            (monthly_income <=
                                            money_of_cents_string("127692598"))):
                                            return (money_of_cents_string("12548507") +
                                                ((monthly_income -
                                                money_of_cents_string("66884015")) *
                                                decimal_of_string("0.3")))
                                        else:
                                            if ((monthly_income >=
                                                money_of_cents_string("127692599")) and
                                                (monthly_income <=
                                                money_of_cents_string("170256797"))):
                                                return (money_of_cents_string("30791081") +
                                                    ((monthly_income -
                                                    money_of_cents_string("127692599")) *
                                                    decimal_of_string("0.32")))
                                            else:
                                                if ((monthly_income >=
                                                    money_of_cents_string("170256798")) and
                                                    (monthly_income <=
                                                    money_of_cents_string("510770392"))):
                                                    return (money_of_cents_string("44405791") +
                                                        ((monthly_income -
                                                        money_of_cents_string("170256798")) *
                                                        decimal_of_string("0.34")))
                                                else:
                                                    return (money_of_cents_string("160567959") +
                                                        ((monthly_income -
                                                        money_of_cents_string("510770393")) *
                                                        decimal_of_string("0.35")))
        def temp_tax_owed_1(_:Unit):
            return True
        temp_tax_owed_2 = handle_default(SourcePosition(filename="engines/catala/lisr.catala_en",
                                         start_line=20, start_column=10,
                                         end_line=20, end_column=18,
                                         law_headings=[]), [],
                                         temp_tax_owed_1, temp_tax_owed)
    except EmptyError:
        temp_tax_owed_2 = dead_value
        raise NoValueProvided(SourcePosition(filename="engines/catala/lisr.catala_en",
                                             start_line=20, start_column=10,
                                             end_line=20, end_column=18,
                                             law_headings=[]))
    tax_owed = temp_tax_owed_2
    return TaxCalculation2026(tax_owed = tax_owed)
